name: CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.1
      with:
        node-version: 12
    - name: Install dependencies
      run: npm install
    - name: Test
      run: npm test
    - name: Build
      run: npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
  deploy:
    if: ${{ github.event_name == 'pull_request' }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: build
    - run: ls build
